services:
  dhis2-db:
    image: postgis/postgis:13-3.3
    container_name: dhis2-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dhis2_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dhis2-network

  dhis2-core:
    image: dhis2/core:2.40.7
    container_name: dhis2-core
    environment:
      DHIS2_DATABASE_HOST: ${DHIS2_DATABASE_HOST}
      DHIS2_DATABASE_PORT: ${DHIS2_DATABASE_PORT}
      DHIS2_DATABASE_NAME: ${DHIS2_DATABASE_NAME}
      DHIS2_DATABASE_USERNAME: ${DHIS2_DATABASE_USERNAME}
      DHIS2_DATABASE_PASSWORD: ${DHIS2_DATABASE_PASSWORD}
      DHIS2_AUDIT_DATABASE_HOST: ${DHIS2_AUDIT_DATABASE_HOST}
      DHIS2_AUDIT_DATABASE_PORT: ${DHIS2_AUDIT_DATABASE_PORT}
      DHIS2_AUDIT_DATABASE_NAME: ${DHIS2_AUDIT_DATABASE_NAME}
      DHIS2_AUDIT_DATABASE_USERNAME: ${DHIS2_AUDIT_DATABASE_USERNAME}
      DHIS2_AUDIT_DATABASE_PASSWORD: ${DHIS2_AUDIT_DATABASE_PASSWORD}
    ports:
      - "9831:8080"
    depends_on:
      - dhis2-db
    networks:
      - dhis2-network
    volumes:
      - ./config/dhis.conf:/opt/dhis2/dhis.conf

volumes:
  dhis2_db_data:

networks:
  dhis2-network:
    driver: bridge
